### ISSUE TITLE
Issue when updating passwords

### ISSUE THREAD

**Issue by PassiveModding** [riggraz/astuto#10]
`Errno::EADDRNOTAVAIL (Cannot assign requested address - connect(2) for "localhost" port 25):`

**Comment by riggraz** [comment]
Hi PassiveModding,

could you please be more specific? Are you experiencing this issue when changing postgres password in the `.env` file? Or something else?

**Comment by PassiveModding** [comment]
this is when registering a new user or updating a password in the users page
