### ISSUE TITLE
Improve installation process: create Docker image and upload to DockerHub

### ISSUE THREAD

**Issue by stefaanv** [riggraz/astuto#17]
I'd like to try Astuto to capture internal user feedback, but find the installation rather unusual.
Docker images are not meant to be changed after being built neither should they be built on purpose for every deployment.
Better get rid of the .env file and have the environment variables injected into the container at startup by docker-compose.  That way, you can share a universal (configuration-less) image to docker hub together with an example docker-compose file.
IT ops people can then download the docker-compose file, adapt it and start it, everything else will be handled by docker-compose.
Let me know if I can help in any way

**Comment by riggraz** [comment]
Hi stefaanv, sorry for being so late in my answer.

You're definitely right, that would be an easier and cleaner installation process. If you'd like to contribute you're more than welcome! Otherwise I'll work on it when I have some spare time. Let me know.

Thanks again for taking the time to open this issue. Bye!

**Comment by ImaCrea** [comment]
that'd be great @stefaanv 💎
Also at the moment, I could only test it in a local environment but then I'm lost. I don't have much knowledge with Docker other than following instructions and I'd love to make it work and start collecting actual users feedbacks. Would love to try it with MailTape community ☺️

**Comment by pwnyprod** [comment]
The Docker Image should be build by maintainer and not on every project. so it will be nice if you build the image to DockerHub and just provide a docker-compose example in the readme so the user dont need to pull the src.

**Comment by ntatko** [comment]
It looks like your docker compose pretty much just spins up a postgres instance and your web service. To put this on dockerhub, pretty much, you just need to build and push your existing UI docker image to dockerhub. Should be super easy. You'll need to add a few parameters: `POSTGRES_URL` and `POSTGRES_DB` OR you could be clever and use the connection string format `POSTGRES_CONNECTION_STRING` which would look like `postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]`.(see [this stackoverflow answer](https://stackoverflow.com/questions/3582552/postgresql-connection-url) for details). 

It may mean some changes need to be made on initialization - db setup and what not. I haven't looked deeply yet, but on the whole, this seems pretty simple.

**Comment by riggraz** [comment]
Thanks for the suggestions ntatko!

I'll probably work on this feature next week, I'll keep you updated.

**Comment by riggraz** [comment]
Update: I finally published astuto's image on Docker Hub 🥳 You can find it [here](https://hub.docker.com/repository/docker/riggraz/astuto).

There are a lot of things to fix (some warnings, image size too big) but I tested it on both Linux and macOS and it works fine! Anyway if you try it out let me know if it works for you too!

**Comment by pwnyprod** [comment]
Great, so this issue can be closed for now ;)

**Comment by riggraz** [comment]
Yup, I forgot to do it 😅
