### ISSUE TITLE
anny update on this core functionality?

### ISSUE THREAD

**Issue by voicaandrei** [riggraz/astuto#33]
Hi,

First of all, thank you for this great open source project. Do you have anny estimate on those? 
-There must be a setting in user profile to enable/disable email notifications
-An email should be sent when a user gets a reply to a post/comment
-An email should be sent when a post update is published for a followed post

Those are very important things for users who add some feedback, to get back to them and give them an update on their feedback.

Thank You!

**Comment by riggraz** [comment]
I'm closing this issue since I've opened a new one (issue #42) which tackles exactly the implementation of email notifications. Hope to see you there!
