### ISSUE TITLE
update-and-run script returns `unauthorized: Incorrect username or password` for docker ruby image

### ISSUE THREAD

**Issue by arnaudmanaranche** [riggraz/astuto#5]
When i want to launch the project, the following error happened :
```js
➜ script/docker-update-and-run.sh .
Starting update...
-> Docker image will be rebuilt if necessary
-> Database schema will be updated if necessary
-> Webpack will compile assets
db uses an image, skipping
Building web
Step 1/15 : FROM ruby:2.6.3
ERROR: Service 'web' failed to build: Get https://registry-1.docker.io/v2/library/ruby/manifests/2.6.3: unauthorized: incorrect username or password
```
Is it related to ```POSTGRES_USER``` and ```POSTGRES_PASSWORD``` ?

**Comment by riggraz** [comment]
Hi,

thanks for posting.

> Is it related to POSTGRES_USER and POSTGRES_PASSWORD?

No, I'm pretty sure it has something to do with the way you connect to the Docker Hub. Are you using Windows? I've found this [forum post](https://forums.docker.com/t/unauthorized-incorrect-username-or-password/35677/3) that may help you.

**Comment by arnaudmanaranche** [comment]
Running the following command to solved the issue: 
```
$ docker login
```

Thanks @riggraz !
