### ISSUE TITLE
Change master branch into main

### ISSUE THREAD

**Issue by Vin0uz** [riggraz/astuto#50]
Github recently followed the [software freedom consultancy recommendation](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) and renamed master branch as main. 

As it has become the new standard, it should be the case here too :)

**Comment by riggraz** [comment]
Branch renamed as `main` 😉

For anyone who has a local copy of the repository on their machine, here are the git commands to adapt to the new branch name:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by Vin0uz** [comment]
Little note : Remember to rename the one from your forked project if you forked before the change :)
