### ISSUE TITLE
Add OAuth 2 authentication

### ISSUE THREAD

**Issue by riggraz** [riggraz/astuto#52]
Forcing user to sign up with their email is time consuming and may discourage some of them to submit feedback. Hence, we should provide OAuth login with the most popular providers. To start, I think we should:

- Setup OAuth 2
- Configure Facebook, Google and GitHub providers to work with OAuth

**Comment by SocketSomeone** [comment]
**Suggestions:**
- Add Discord provider to work with OAuth
- OAuth 2 only login(Disable login by email & password)

**Comment by riggraz** [comment]
> Add Discord provider to work with OAuth

After OAuth2 will be configured it will be very easy to add providers like Discord or Twitch for example. So yeah, I'd start with the 2 or 3 most common ones (Facebook and Google for sure, maybe GitHub) then if "someone" (double interpretation here ;) wants to add more providers that would be cool!

> OAuth 2 only login(Disable login by email & password)

Can you elaborate on why do you think it'd better to disable email login?

I think that most users will use OAuth login, but that doesn't mean that some people may not have a social account or refuse to use it for privacy concerns. Moreover, since the email login is already there, I see no reasons for removing it.

**Comment by SocketSomeone** [comment]
> Can you elaborate on why do you think it'd better to disable email login?

Just as an additional feature.

I think this is suitable for applications that are targeting use in the context of a given OAuth 2 provider. 
Ex: Dashboard for Discord bot.

**Comment by sbkg0002** [comment]
Adding Azure AD would also make it interesting for a large group of enterprises.

**Comment by riggraz** [comment]
OAuth 2 has been implemented with PR #147 🎉
