### ISSUE TITLE
Add new locales

### ISSUE THREAD

**Issue by CrazyCrud** [riggraz/astuto#57]
First of all, thank you for your hard work on _astuto_.   
I saw that you can add locales in the `config`-folder but I would like to know where exactly I could switch the language displayed to the user?

Thank you in advance.

**Comment by riggraz** [comment]
Hi CrazyCrud 👋🏻 thanks for posting!

I think you can switch locales by adding the following line in `config/application.rb`:

```
config.i18n.default_locale = :de
```

But please note that Astuto does not rely on i18n locales except for a few notifications strings and for the authentication system. This means that nearly all strings right now are hardcoded and won't change even if you define a new locale.

Internationalization, however, is on our todo list, so it may come in the future!

**Comment by CrazyCrud** [comment]
Thank you for your answer.   
> But please note that Astuto does not rely on i18n locales except for a few notifications strings and for the authentication system.    
  
Thank you for this information, I'll then just edit the hardcoded strings.   

Keep up the good work and best regards.
