### ISSUE TITLE
Improve Docker image

### ISSUE THREAD

**Issue by riggraz** [riggraz/astuto#58]
The Docker image of Astuto is working fine (and is finally available on the [Docker Hub](https://hub.docker.com/repository/docker/riggraz/astuto) as well!), but it also has some problems.

- [ ] The image size is big (610MB) and could probably be much smaller
- [x] The node version specified in the Dockerfile (v 11) is deprecated so it should be updated
- [ ] `yarn install` shows some lines of warnings about unmet peer dependencies.
- [ ] `rails assets:precompile` should be run in Dockerfile (hence assets should already be compiled in the image) and not in docker-entrypoint.sh

Moreover, running `docker-compose up` when pulling astuto from Docker Hub displays a warning message (`WARNING: The B variable is not set. Defaulting to a blank string.`).

**Comment by cadavre** [comment]
Ad 1) Use `node:...-slim` image.
Ad comment) It's because of how you enter secret in hex mode. Avoid `$` and other meaningful chars.

**Comment by riggraz** [comment]
A few times this error appeared:

```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/astuto/node_modules/mime'".
info If you think this is a bug, please open a bug report with the information provided in "/astuto/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

If you then docker run again, it works without problems.
