### ISSUE TITLE
Error with other host/ip than localhost

### ISSUE THREAD

**Issue by kyuumeitai** [riggraz/astuto#6]
Hi there, great work!

Whenever I try to use the astuto in a remote machine, there's some errors regarding localhost in development mode

the webpack config in 
config/webpacker.yml ( https://github.com/riggraz/astuto/blob/9e3bf6dd0b0ddd4bdbe7c91cbfaa52a9da552dd7/config/webpacker.yml )
seems to call localhost 

Is there any way to configure the host to run remotely?

Thank you!

**Comment by riggraz** [comment]
Hey kyuumeitai,

thanks for the issue report.

I think the webpack documentation can help you solve the problem: you can use [allowedHosts](https://webpack.js.org/configuration/dev-server/#devserverallowedhosts) to specify hosts that can access the webpack dev server, and [host](https://webpack.js.org/configuration/dev-server/#devserverhost) to specify the host to use. As written in the docs, if you want the server to be accessible externally you should configure `host` to `0.0.0.0`.

In any case, you should manually change the `webpacker.yml` file.

Maybe this infos should be written in the Astuto's docs, or an environment variable in the `.env` file should be responsible of setting `allowedHosts` and `host` in `webpacker.yml`.

Let me know if you are able to solve the problem.
