### ISSUE TITLE
Problem when changing user password

### ISSUE THREAD

**Issue by frouze** [riggraz/astuto#62]
Hello,
I have installed Astuto on an ubuntu serveur using your documentation (installation in a docker, with docker-compose and editing the .env file at the root folder of the application and nothing else). The application is in "production mode" but i tried in "development mode" and my problem is the same : 

I noticed that when i try to edit a user in order to change his password  the application return an error with a generic message :
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

When looking at the log file i can see this kind of information after a part that try to send an email to the user :
 

D, [2021-03-29T15:58:12.666850 #34] DEBUG -- : [c3bfa550-963e-4139-9050-dfdd1f796101]    (0.2ms)  ROLLBACK
I, [2021-03-29T15:58:12.667181 #34]  INFO -- : [c3bfa550-963e-4139-9050-dfdd1f796101] Completed 500 Internal Server Error in 123ms (ActiveRecord: 2.5ms | Allocations: 3375)
F, [2021-03-29T15:58:12.667807 #34] FATAL -- : [c3bfa550-963e-4139-9050-dfdd1f796101]
[c3bfa550-963e-4139-9050-dfdd1f796101] Errno::EADDRNOTAVAIL (Cannot assign requested address - connect(2) for "localhost" port 25):
[c3bfa550-963e-4139-9050-dfdd1f796101]
[c3bfa550-963e-4139-9050-dfdd1f796101] app/controllers/admin/users_controller.rb:53:in `update'

I suppose i need to configure smtp server somewhere inside the container but i don't have find where to do it.

Could you please give me some information about that ?

Thank's

**Comment by lalejand** [comment]
@riggraz do you have some hint about that ?

**Comment by ericrdgz** [comment]
I am also facing this same issue. Kind of an immediate blocker because I can't change the password for the default admin which is a big security risk to use this for my live product and customers. I have EMAIL_CONFIRMATION=no in my .env file and so I am not sure why it would even be trying to send any emails.

**Comment by riggraz** [comment]
Sorry for the delay, but project development was stopped and resumed only a few months ago. I'll definitely look into this bug as soon as possible.

In the meanwhile, as a workaround, you could create a new user account and make it administrator (you can do this from Site settings > Users). Then, delete the admin@example.com account (log in with it and go to Profile settings > Cancel account).
