### ISSUE TITLE
mimemagic gem is retired ?

### ISSUE THREAD

**Issue by bertrandgorge** [riggraz/astuto#63]
Hello,

I had an issue when trying to install : apparently the mimemagic gem needs to be upgraded... I'm very new to ruby, so I'm not sure I can fix it by myself:

```
 > [ 9/12] RUN bundle install:
#14 0.653 The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
#14 4.334 Fetching gem metadata from https://rubygems.org/............
#14 6.231 Your bundle is locked to mimemagic (0.3.3), but that version could not be found
#14 6.231 in any of the sources listed in your Gemfile. If you haven't changed sources,
#14 6.231 that means the author of mimemagic (0.3.3) has removed it. You'll need to update
#14 6.231 your bundle to a version other than mimemagic (0.3.3) that hasn't been removed
#14 6.231 in order to install.
```

I tried to change the version directly in the lock file but it's not sufficient, one needs to run `bundle update mimemagic` - but I can't as I couldn't build the container...

**Comment by riggraz** [comment]
Thanks for pointing it out, I searched the internet and found there have been quite some problems regarding `mimemagic`. I'll find a way around.

In the meanwhile, if you want to test astuto, you can follow the instructions on [Docker Hub](https://hub.docker.com/r/riggraz/astuto): the astuto image there still works.

**Comment by riggraz** [comment]
The problem should be fixed now. See PR #64 and, if you have time, test it out and let me know if it works!
